
pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage('Checkout SCM'){
            steps{
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/shreyishere/pdf-hero-infra.git']])
                }
            }
        }
        stage('Initializing terraform'){
            steps {
                script {
                    dir('eks') {
                        sh 'terraform init'
                        
                    }
                }
            }
        }
        stage('Validating terraform'){
            steps {
                script {
                    dir('eks') {
                        sh 'terraform validate'
                        
                    }
                }
            }
        }
        stage('Preview infra using terraform'){
            steps {
                script {
                    dir('eks') {
                        sh 'terraform plan'
                    }
                    input(message: "Are you sure to proceed?", ok: "Proceed")
                }
            }
        }
        stage('Apply/Destroy changes'){
            steps {
                script {
                    dir('eks') {
                        sh 'terraform $action --auto-approve'
                        
                    }
                }
            }
        }
        stage('Deploy nginx application') {
            steps {
                script {
                    dir('kubernetes') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster'
                        sh 'kubectl apply -f deployment.yaml'
                        sh 'kubectl apply -f service.yaml'
                    }
                }
            }
        }
    }
}